apiVersion: v1
kind: Service
metadata:
  name: server-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    name: http
  - port: 8039
    targetPort: 8039
    name: presence
  selector:
    app: server
