apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb.fullname" . }}-service
spec:
  ports:
  - port: {{ .Values.database.port }}
    targetPort: {{ .Values.database.port }}
    protocol: TCP
  selector:
    app: {{ template "mongodb.fullname" . }}-pod
