apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb
    spec:
      volumes:
      - name: nfs-volume
        nfs:
          server: {{ .Values.serverVolume.server }}
          path: /sugarizer_vol/sugarizer-server/docker/db
      containers:
      - name: mongodb
        image: {{ .Values.database.image }}
        volumeMounts:
        - name: nfs-volume
          mountPath: /data/db
        command: ["/bin/sh", "-c"]
        args: ["mongod --repair; mongod"]
        env:
        - name: AUTH
          value: "no"
        ports:
        - name: mongodb
          containerPort: {{ .Values.database.port }}
          hostPort: {{ .Values.database.port }}
          protocol: TCP
