apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
        app: server
  template:
    metadata:
        name: server-pod
        labels:
          app: server
    spec:
      volumes:
        - name: {{ .Values.serverVolume.name }}
          nfs:
            server: {{ .Values.serverVolume.server }}
            path: {{ .Values.serverVolume.path }}
        - name: {{ .Values.clientVolume.name }}
          nfs:
            server: {{ .Values.clientVolume.server }}
            path: {{ .Values.clientVolume.path }}
      containers:
      - name: sugarizer-server
        image: {{ .Values.server.image }}
        volumeMounts:
        - name: {{ .Values.serverVolume.name }}
          mountPath: {{ .Values.serverVolume.mountPath }}
        - name: {{ .Values.clientVolume.name }}
          mountPath: {{ .Values.clientVolume.mountPath }}
        workingDir: /sugarizer-server
        command: ["/bin/sh", "-c"]
        args: ["npm install; node /sugarizer-server/sugarizer.js /sugarizer-server/env/docker.ini"]
        env:
        - name: NODE_ENV
          value: docker
        - name: MONGO_URL
          value: mongodb://mongodb.default.svc.cluster.local:{{ .Values.database.port }}/
        ports:
        - containerPort: {{ .Values.server.httpPortPod }}
          name: http
        - containerPort: {{ .Values.server.presencePort }}
          name: presence
